name: fermipy

channels:
  - conda-forge
  - fermi
  - conda-forge/label/cf201901

dependencies:
  - fermitools
  - fermipy
#  - scipy
#  - matplotlib
#  - pyyaml
#  - numpy
#  - astropy
#  - gammapy
#  - healpy
